# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/user/Desktop/CPSC/CPSC 427/AIphaGo Away"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/user/Desktop/CPSC/CPSC 427/AIphaGo Away"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/user/Desktop/CPSC/CPSC 427/AIphaGo Away/CMakeFiles" "/Users/user/Desktop/CPSC/CPSC 427/AIphaGo Away//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/user/Desktop/CPSC/CPSC 427/AIphaGo Away/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AlphaGo-Away

# Build rule for target.
AlphaGo-Away: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlphaGo-Away
.PHONY : AlphaGo-Away

# fast build rule for target.
AlphaGo-Away/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/build
.PHONY : AlphaGo-Away/fast

src/components/motion.o: src/components/motion.cpp.o

.PHONY : src/components/motion.o

# target to build an object file
src/components/motion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/components/motion.cpp.o
.PHONY : src/components/motion.cpp.o

src/components/motion.i: src/components/motion.cpp.i

.PHONY : src/components/motion.i

# target to preprocess a source file
src/components/motion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/components/motion.cpp.i
.PHONY : src/components/motion.cpp.i

src/components/motion.s: src/components/motion.cpp.s

.PHONY : src/components/motion.s

# target to generate assembly for a file
src/components/motion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/components/motion.cpp.s
.PHONY : src/components/motion.cpp.s

src/core/common.o: src/core/common.cpp.o

.PHONY : src/core/common.o

# target to build an object file
src/core/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/common.cpp.o
.PHONY : src/core/common.cpp.o

src/core/common.i: src/core/common.cpp.i

.PHONY : src/core/common.i

# target to preprocess a source file
src/core/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/common.cpp.i
.PHONY : src/core/common.cpp.i

src/core/common.s: src/core/common.cpp.s

.PHONY : src/core/common.s

# target to generate assembly for a file
src/core/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/common.cpp.s
.PHONY : src/core/common.cpp.s

src/core/factories.o: src/core/factories.cpp.o

.PHONY : src/core/factories.o

# target to build an object file
src/core/factories.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/factories.cpp.o
.PHONY : src/core/factories.cpp.o

src/core/factories.i: src/core/factories.cpp.i

.PHONY : src/core/factories.i

# target to preprocess a source file
src/core/factories.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/factories.cpp.i
.PHONY : src/core/factories.cpp.i

src/core/factories.s: src/core/factories.cpp.s

.PHONY : src/core/factories.s

# target to generate assembly for a file
src/core/factories.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/factories.cpp.s
.PHONY : src/core/factories.cpp.s

src/core/game.o: src/core/game.cpp.o

.PHONY : src/core/game.o

# target to build an object file
src/core/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/game.cpp.o
.PHONY : src/core/game.cpp.o

src/core/game.i: src/core/game.cpp.i

.PHONY : src/core/game.i

# target to preprocess a source file
src/core/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/game.cpp.i
.PHONY : src/core/game.cpp.i

src/core/game.s: src/core/game.cpp.s

.PHONY : src/core/game.s

# target to generate assembly for a file
src/core/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/game.cpp.s
.PHONY : src/core/game.cpp.s

src/core/loader.o: src/core/loader.cpp.o

.PHONY : src/core/loader.o

# target to build an object file
src/core/loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/loader.cpp.o
.PHONY : src/core/loader.cpp.o

src/core/loader.i: src/core/loader.cpp.i

.PHONY : src/core/loader.i

# target to preprocess a source file
src/core/loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/loader.cpp.i
.PHONY : src/core/loader.cpp.i

src/core/loader.s: src/core/loader.cpp.s

.PHONY : src/core/loader.s

# target to generate assembly for a file
src/core/loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/loader.cpp.s
.PHONY : src/core/loader.cpp.s

src/core/map.o: src/core/map.cpp.o

.PHONY : src/core/map.o

# target to build an object file
src/core/map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/map.cpp.o
.PHONY : src/core/map.cpp.o

src/core/map.i: src/core/map.cpp.i

.PHONY : src/core/map.i

# target to preprocess a source file
src/core/map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/map.cpp.i
.PHONY : src/core/map.cpp.i

src/core/map.s: src/core/map.cpp.s

.PHONY : src/core/map.s

# target to generate assembly for a file
src/core/map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/map.cpp.s
.PHONY : src/core/map.cpp.s

src/core/registry.o: src/core/registry.cpp.o

.PHONY : src/core/registry.o

# target to build an object file
src/core/registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/registry.cpp.o
.PHONY : src/core/registry.cpp.o

src/core/registry.i: src/core/registry.cpp.i

.PHONY : src/core/registry.i

# target to preprocess a source file
src/core/registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/registry.cpp.i
.PHONY : src/core/registry.cpp.i

src/core/registry.s: src/core/registry.cpp.s

.PHONY : src/core/registry.s

# target to generate assembly for a file
src/core/registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/registry.cpp.s
.PHONY : src/core/registry.cpp.s

src/core/unitmap.o: src/core/unitmap.cpp.o

.PHONY : src/core/unitmap.o

# target to build an object file
src/core/unitmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/unitmap.cpp.o
.PHONY : src/core/unitmap.cpp.o

src/core/unitmap.i: src/core/unitmap.cpp.i

.PHONY : src/core/unitmap.i

# target to preprocess a source file
src/core/unitmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/unitmap.cpp.i
.PHONY : src/core/unitmap.cpp.i

src/core/unitmap.s: src/core/unitmap.cpp.s

.PHONY : src/core/unitmap.s

# target to generate assembly for a file
src/core/unitmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/core/unitmap.cpp.s
.PHONY : src/core/unitmap.cpp.s

src/entities/human_terminator.o: src/entities/human_terminator.cpp.o

.PHONY : src/entities/human_terminator.o

# target to build an object file
src/entities/human_terminator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/entities/human_terminator.cpp.o
.PHONY : src/entities/human_terminator.cpp.o

src/entities/human_terminator.i: src/entities/human_terminator.cpp.i

.PHONY : src/entities/human_terminator.i

# target to preprocess a source file
src/entities/human_terminator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/entities/human_terminator.cpp.i
.PHONY : src/entities/human_terminator.cpp.i

src/entities/human_terminator.s: src/entities/human_terminator.cpp.s

.PHONY : src/entities/human_terminator.s

# target to generate assembly for a file
src/entities/human_terminator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/entities/human_terminator.cpp.s
.PHONY : src/entities/human_terminator.cpp.s

src/entities/unit.o: src/entities/unit.cpp.o

.PHONY : src/entities/unit.o

# target to build an object file
src/entities/unit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/entities/unit.cpp.o
.PHONY : src/entities/unit.cpp.o

src/entities/unit.i: src/entities/unit.cpp.i

.PHONY : src/entities/unit.i

# target to preprocess a source file
src/entities/unit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/entities/unit.cpp.i
.PHONY : src/entities/unit.cpp.i

src/entities/unit.s: src/entities/unit.cpp.s

.PHONY : src/entities/unit.s

# target to generate assembly for a file
src/entities/unit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/entities/unit.cpp.s
.PHONY : src/entities/unit.cpp.s

src/gui/gui.o: src/gui/gui.cpp.o

.PHONY : src/gui/gui.o

# target to build an object file
src/gui/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/gui.cpp.o
.PHONY : src/gui/gui.cpp.o

src/gui/gui.i: src/gui/gui.cpp.i

.PHONY : src/gui/gui.i

# target to preprocess a source file
src/gui/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/gui.cpp.i
.PHONY : src/gui/gui.cpp.i

src/gui/gui.s: src/gui/gui.cpp.s

.PHONY : src/gui/gui.s

# target to generate assembly for a file
src/gui/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/gui.cpp.s
.PHONY : src/gui/gui.cpp.s

src/gui/imgui_impl_glfw.o: src/gui/imgui_impl_glfw.cpp.o

.PHONY : src/gui/imgui_impl_glfw.o

# target to build an object file
src/gui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/imgui_impl_glfw.cpp.o
.PHONY : src/gui/imgui_impl_glfw.cpp.o

src/gui/imgui_impl_glfw.i: src/gui/imgui_impl_glfw.cpp.i

.PHONY : src/gui/imgui_impl_glfw.i

# target to preprocess a source file
src/gui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/imgui_impl_glfw.cpp.i
.PHONY : src/gui/imgui_impl_glfw.cpp.i

src/gui/imgui_impl_glfw.s: src/gui/imgui_impl_glfw.cpp.s

.PHONY : src/gui/imgui_impl_glfw.s

# target to generate assembly for a file
src/gui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/imgui_impl_glfw.cpp.s
.PHONY : src/gui/imgui_impl_glfw.cpp.s

src/gui/imgui_impl_opengl3.o: src/gui/imgui_impl_opengl3.cpp.o

.PHONY : src/gui/imgui_impl_opengl3.o

# target to build an object file
src/gui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/imgui_impl_opengl3.cpp.o
.PHONY : src/gui/imgui_impl_opengl3.cpp.o

src/gui/imgui_impl_opengl3.i: src/gui/imgui_impl_opengl3.cpp.i

.PHONY : src/gui/imgui_impl_opengl3.i

# target to preprocess a source file
src/gui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/imgui_impl_opengl3.cpp.i
.PHONY : src/gui/imgui_impl_opengl3.cpp.i

src/gui/imgui_impl_opengl3.s: src/gui/imgui_impl_opengl3.cpp.s

.PHONY : src/gui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/gui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/gui/imgui_impl_opengl3.cpp.s
.PHONY : src/gui/imgui_impl_opengl3.cpp.s

src/logger/debug.o: src/logger/debug.cpp.o

.PHONY : src/logger/debug.o

# target to build an object file
src/logger/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/logger/debug.cpp.o
.PHONY : src/logger/debug.cpp.o

src/logger/debug.i: src/logger/debug.cpp.i

.PHONY : src/logger/debug.i

# target to preprocess a source file
src/logger/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/logger/debug.cpp.i
.PHONY : src/logger/debug.cpp.i

src/logger/debug.s: src/logger/debug.cpp.s

.PHONY : src/logger/debug.s

# target to generate assembly for a file
src/logger/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/logger/debug.cpp.s
.PHONY : src/logger/debug.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/system/ai.o: src/system/ai.cpp.o

.PHONY : src/system/ai.o

# target to build an object file
src/system/ai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/ai.cpp.o
.PHONY : src/system/ai.cpp.o

src/system/ai.i: src/system/ai.cpp.i

.PHONY : src/system/ai.i

# target to preprocess a source file
src/system/ai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/ai.cpp.i
.PHONY : src/system/ai.cpp.i

src/system/ai.s: src/system/ai.cpp.s

.PHONY : src/system/ai.s

# target to generate assembly for a file
src/system/ai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/ai.cpp.s
.PHONY : src/system/ai.cpp.s

src/system/particleSystem.o: src/system/particleSystem.cpp.o

.PHONY : src/system/particleSystem.o

# target to build an object file
src/system/particleSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/particleSystem.cpp.o
.PHONY : src/system/particleSystem.cpp.o

src/system/particleSystem.i: src/system/particleSystem.cpp.i

.PHONY : src/system/particleSystem.i

# target to preprocess a source file
src/system/particleSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/particleSystem.cpp.i
.PHONY : src/system/particleSystem.cpp.i

src/system/particleSystem.s: src/system/particleSystem.cpp.s

.PHONY : src/system/particleSystem.s

# target to generate assembly for a file
src/system/particleSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/particleSystem.cpp.s
.PHONY : src/system/particleSystem.cpp.s

src/system/physics.o: src/system/physics.cpp.o

.PHONY : src/system/physics.o

# target to build an object file
src/system/physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/physics.cpp.o
.PHONY : src/system/physics.cpp.o

src/system/physics.i: src/system/physics.cpp.i

.PHONY : src/system/physics.i

# target to preprocess a source file
src/system/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/physics.cpp.i
.PHONY : src/system/physics.cpp.i

src/system/physics.s: src/system/physics.cpp.s

.PHONY : src/system/physics.s

# target to generate assembly for a file
src/system/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/physics.cpp.s
.PHONY : src/system/physics.cpp.s

src/system/render.o: src/system/render.cpp.o

.PHONY : src/system/render.o

# target to build an object file
src/system/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render.cpp.o
.PHONY : src/system/render.cpp.o

src/system/render.i: src/system/render.cpp.i

.PHONY : src/system/render.i

# target to preprocess a source file
src/system/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render.cpp.i
.PHONY : src/system/render.cpp.i

src/system/render.s: src/system/render.cpp.s

.PHONY : src/system/render.s

# target to generate assembly for a file
src/system/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render.cpp.s
.PHONY : src/system/render.cpp.s

src/system/render_components.o: src/system/render_components.cpp.o

.PHONY : src/system/render_components.o

# target to build an object file
src/system/render_components.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render_components.cpp.o
.PHONY : src/system/render_components.cpp.o

src/system/render_components.i: src/system/render_components.cpp.i

.PHONY : src/system/render_components.i

# target to preprocess a source file
src/system/render_components.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render_components.cpp.i
.PHONY : src/system/render_components.cpp.i

src/system/render_components.s: src/system/render_components.cpp.s

.PHONY : src/system/render_components.s

# target to generate assembly for a file
src/system/render_components.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render_components.cpp.s
.PHONY : src/system/render_components.cpp.s

src/system/render_init.o: src/system/render_init.cpp.o

.PHONY : src/system/render_init.o

# target to build an object file
src/system/render_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render_init.cpp.o
.PHONY : src/system/render_init.cpp.o

src/system/render_init.i: src/system/render_init.cpp.i

.PHONY : src/system/render_init.i

# target to preprocess a source file
src/system/render_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render_init.cpp.i
.PHONY : src/system/render_init.cpp.i

src/system/render_init.s: src/system/render_init.cpp.s

.PHONY : src/system/render_init.s

# target to generate assembly for a file
src/system/render_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/render_init.cpp.s
.PHONY : src/system/render_init.cpp.s

src/system/utils/a_star.o: src/system/utils/a_star.cpp.o

.PHONY : src/system/utils/a_star.o

# target to build an object file
src/system/utils/a_star.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/utils/a_star.cpp.o
.PHONY : src/system/utils/a_star.cpp.o

src/system/utils/a_star.i: src/system/utils/a_star.cpp.i

.PHONY : src/system/utils/a_star.i

# target to preprocess a source file
src/system/utils/a_star.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/utils/a_star.cpp.i
.PHONY : src/system/utils/a_star.cpp.i

src/system/utils/a_star.s: src/system/utils/a_star.cpp.s

.PHONY : src/system/utils/a_star.s

# target to generate assembly for a file
src/system/utils/a_star.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/utils/a_star.cpp.s
.PHONY : src/system/utils/a_star.cpp.s

src/system/utils/kd-tree.o: src/system/utils/kd-tree.cpp.o

.PHONY : src/system/utils/kd-tree.o

# target to build an object file
src/system/utils/kd-tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/utils/kd-tree.cpp.o
.PHONY : src/system/utils/kd-tree.cpp.o

src/system/utils/kd-tree.i: src/system/utils/kd-tree.cpp.i

.PHONY : src/system/utils/kd-tree.i

# target to preprocess a source file
src/system/utils/kd-tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/utils/kd-tree.cpp.i
.PHONY : src/system/utils/kd-tree.cpp.i

src/system/utils/kd-tree.s: src/system/utils/kd-tree.cpp.s

.PHONY : src/system/utils/kd-tree.s

# target to generate assembly for a file
src/system/utils/kd-tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaGo-Away.dir/build.make CMakeFiles/AlphaGo-Away.dir/src/system/utils/kd-tree.cpp.s
.PHONY : src/system/utils/kd-tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AlphaGo-Away"
	@echo "... src/components/motion.o"
	@echo "... src/components/motion.i"
	@echo "... src/components/motion.s"
	@echo "... src/core/common.o"
	@echo "... src/core/common.i"
	@echo "... src/core/common.s"
	@echo "... src/core/factories.o"
	@echo "... src/core/factories.i"
	@echo "... src/core/factories.s"
	@echo "... src/core/game.o"
	@echo "... src/core/game.i"
	@echo "... src/core/game.s"
	@echo "... src/core/loader.o"
	@echo "... src/core/loader.i"
	@echo "... src/core/loader.s"
	@echo "... src/core/map.o"
	@echo "... src/core/map.i"
	@echo "... src/core/map.s"
	@echo "... src/core/registry.o"
	@echo "... src/core/registry.i"
	@echo "... src/core/registry.s"
	@echo "... src/core/unitmap.o"
	@echo "... src/core/unitmap.i"
	@echo "... src/core/unitmap.s"
	@echo "... src/entities/human_terminator.o"
	@echo "... src/entities/human_terminator.i"
	@echo "... src/entities/human_terminator.s"
	@echo "... src/entities/unit.o"
	@echo "... src/entities/unit.i"
	@echo "... src/entities/unit.s"
	@echo "... src/gui/gui.o"
	@echo "... src/gui/gui.i"
	@echo "... src/gui/gui.s"
	@echo "... src/gui/imgui_impl_glfw.o"
	@echo "... src/gui/imgui_impl_glfw.i"
	@echo "... src/gui/imgui_impl_glfw.s"
	@echo "... src/gui/imgui_impl_opengl3.o"
	@echo "... src/gui/imgui_impl_opengl3.i"
	@echo "... src/gui/imgui_impl_opengl3.s"
	@echo "... src/logger/debug.o"
	@echo "... src/logger/debug.i"
	@echo "... src/logger/debug.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/system/ai.o"
	@echo "... src/system/ai.i"
	@echo "... src/system/ai.s"
	@echo "... src/system/particleSystem.o"
	@echo "... src/system/particleSystem.i"
	@echo "... src/system/particleSystem.s"
	@echo "... src/system/physics.o"
	@echo "... src/system/physics.i"
	@echo "... src/system/physics.s"
	@echo "... src/system/render.o"
	@echo "... src/system/render.i"
	@echo "... src/system/render.s"
	@echo "... src/system/render_components.o"
	@echo "... src/system/render_components.i"
	@echo "... src/system/render_components.s"
	@echo "... src/system/render_init.o"
	@echo "... src/system/render_init.i"
	@echo "... src/system/render_init.s"
	@echo "... src/system/utils/a_star.o"
	@echo "... src/system/utils/a_star.i"
	@echo "... src/system/utils/a_star.s"
	@echo "... src/system/utils/kd-tree.o"
	@echo "... src/system/utils/kd-tree.i"
	@echo "... src/system/utils/kd-tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

